FROM erlang:22

ENV LOG_DIR "/var/minidote/logs"
ENV OP_LOG_DIR "/var/minidote/op_log"
ENV MINIDOTE_POOL_SIZE 100
ENV MINIDOTE_PORT 8087
ENV MINIDOTE_MAX_CONNECTIONS 1024
ENV CAMUS_PORT 6866

# PB Port for Minidote
EXPOSE 8087
# Port for CAMUS
EXPOSE 6866

COPY . /tmp/minidote
WORKDIR /tmp/minidote

RUN make rel
RUN cp -r _build/default/rel/minidote /minidote

WORKDIR /minidote

CMD ["bin/env"]
