FROM erlang:22

ENV LOG_DIR "/var/minidote/logs"
ENV OP_LOG_DIR "/var/minidote/op_log"
ENV MINIDOTE_POOL_SIZE 100
ENV MINIDOTE_PORT 8087
ENV MINIDOTE_MAX_CONNECTIONS 1024
ENV CAMUS_PORT 6866

# PB Port for Minidote
EXPOSE 8087
# Port for CAMUS
EXPOSE 6866

ENV NAME=/minidote

COPY . /tmp/minidote

RUN cd /tmp/minidote \
    && make rel \
    && cp -r _build/default/rel/$NAME $NAME

WORKDIR $NAME

CMD ["bin/env"]
